# Generated by Django 5.1.2 on 2024-11-15 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auditlog_changes_alter_auditlog_target_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='assigned_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='clientprogress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress', to='api.client'),
        ),
        migrations.AlterField(
            model_name='clientprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress', to='api.trainingmodule'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.employerprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.client'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='api.client'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='api.trainingmodule'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_sessions', to='api.employeeprofile'),
        ),
    ]
